import 'package:flutter/material.dart';
import 'package:flutter_chat_ui/flutter_chat_ui.dart';

class PrivacyPolicy extends StatefulWidget {
  const PrivacyPolicy({super.key});

  @override
  State<PrivacyPolicy> createState() => _PrivacyPolicyState();
}

class _PrivacyPolicyState extends State<PrivacyPolicy> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "Privacy Policy",
          style: Theme.of(context).textTheme.titleLarge,
        ),
      ),
      body: SingleChildScrollView(
        child: Container(
          margin: const EdgeInsets.only(
              top: 10, bottom: 40, left: 20, right: 20),
          width: MediaQuery.sizeOf(context).width,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                width: MediaQuery.sizeOf(context).width,
                child: RichText(
                  textAlign: TextAlign.start,
                  text: TextSpan(
                    text: 'Last updated: August 6, 2024',
                    style: Theme.of(context)
                        .textTheme
                        .bodyMedium
                        ?.copyWith(
                            color: Colors.deepPurple[50]
                                ?.withOpacity(0.7)),
                  ),
                ),
              ),
              const SizedBox(
                height: 10,
              ),
              paragraphNormal(context,
                  'This Privacy Policy describes our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.'),
              const SizedBox(
                height: 10,
              ),
              paragraphNormal(context,
                  'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.'),
              const SizedBox(
                height: 15,
              ),
              titleText(context, 'Interpretation'),
              const SizedBox(
                height: 10,
              ),
              paragraphNormal(context,
                  'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.'),
              const SizedBox(
                height: 10,
              ),
              titleText(context, 'Definitions'),
              const SizedBox(
                height: 15,
              ),
              paragraphNormal(context,
                  '\t 1. Account means a unique account created for You to access our Service or parts of our Service.\n\n\t 2. Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n\n\t 3. Application refers to DermAI, the software program provided by the Company. \n\n\t 4. Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to DermAI.\n\n\t5. Country refers to: Mauritius\n\n\t6. Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n\n\t7. Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.\n\n\t8. Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n\n\t 9. You, means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.'),
              SizedBox(
                height: 10,
              ),
              titleText(
                  context, 'Collecting and Using Your Personal Data'),
              SizedBox(
                height: 15,
              ),
              titleText(context, 'Personal Data'),
              SizedBox(
                height: 10,
              ),
              paragraphNormal(context,
                  'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, Phone number, Usage Data'),
              SizedBox(
                height: 10,
              ),
              titleText(context, 'Usage Data'),
              paragraphNormal(context,
                  'Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device\'s Internet Protocol address e.g. IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\n When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\n We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.\n\n Information Collected while Using the Application While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission: \n\nPictures and other information from your Device\'s camera and photo library. \n\nWe use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company\'s servers and or a Service Provider\'s server or it may be simply stored on Your device. \n\nYou can enable or disable access to this information at any time, through Your Device settings. Use of Your Personal Data The Company may use Personal Data for the following purposes:'),
              SizedBox(
                height: 15,
              ),
              paragraphNormal(context,
                  'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party\'s site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.\n\nChanges to this Privacy Policy We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\nWe will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy')
            ],
          ),
        ),
      ),
    );
  }

  Container titleText(BuildContext context, String titleMessage) {
    return Container(
      width: MediaQuery.sizeOf(context).width,
      // color: Colors.amber,
      child: RichText(
          textAlign: TextAlign.start,
          text: TextSpan(
              text: titleMessage,
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.w600,
                  ))),
    );
  }

  RichText paragraphNormal(
      BuildContext context, String paragraphMessage) {
    return RichText(
      textAlign: TextAlign.justify,
      text: TextSpan(
          text: paragraphMessage,
          style: Theme.of(context)
              .textTheme
              .bodyMedium
              ?.copyWith(fontSize: 15)),
    );
  }
}
